USE DiebmannImobiliare

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRAN
	SELECT * FROM Agenti
	WAITFOR DELAY '00:00:15'
	SELECT * FROM Agenti
COMMIT TRAN


